Programming Assignment 

Yash Goyal

24110399


#### Question 1

In [14]:
import numpy as np
import time

# this is the jacobi method 
def jac(a, b):
    n = len(b)
    x = np.zeros(n)
    d = np.diag(a)
    r = a - np.diagflat(d)
    it = 0
    while True:
        it += 1
        x2 = (b - np.dot(r, x)) / d
        if np.linalg.norm(x2 - x, np.inf) < 1e-6:
            return x2, it
        if it > 100000:
            return x2, it
        x = x2

# Similarly this wil give the ans 
# using the gauss seidel method 
def gs(a, b):
    n = len(b)
    x = np.zeros(n)
    it = 0
    
    while True:
        it += 1
        old = x.copy()
        for i in range(n):
            s1 = np.dot(a[i, :i], x[:i])
            s2 = np.dot(a[i, i+1:], old[i+1:])
            x[i] = (b[i] - s1 - s2) / a[i][i]
        if np.linalg.norm(x - old, np.inf) < 1e-6:
            return x, it
        if it > 100000:
            return x, it

# matrix 
def do(n):
    a = np.zeros((n, n))
    b = np.full(n, 5)
    
    for i in range(n):
        a[i][i] = 4 + 2*1
        if i < n-1:
            a[i][i+1] = -1
            a[i+1][i] = -1
    return a, b

# ans with gaussian elm method 
def gauss(a, b):
    a = a.copy().astype(float)
    b = b.copy().astype(float)
    n = len(b)
    for k in range(n-1):
        p = k + np.argmax(abs(a[k:, k]))
        if abs(a[p][k]) < 1e-14:
            print("not defined")
            return
        if p != k:
            a[[k, p]] = a[[p, k]]
            b[[k, p]] = b[[p, k]]
            
        for i in range(k+1, n):
            f = a[i][k] / a[k][k]
            a[i, k:] = a[i, k:] - f * a[k, k:]
            b[i] = b[i] - f * b[k]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(a[i, i+1:], x[i+1:])) / a[i][i]
    return x

arr = [5, 10, 20, 50]
res = []

for n in arr:
    a, b = do(n)
    t = time.time()
    x1 = gauss(a, b)
    t1 = time.time() - t
    t = time.time()
    x2, it1 = jac(a, b)
    t2 = time.time() - t
    t = time.time()
    x3, it2 = gs(a, b)
    t3 = time.time() - t
    res.append((n, x1, x2, x3, it1, it2, t1, t2, t3))


for i in res:
    print("")
    print("n =", i[0])
    print("gaussian elimination:")
    print(i[1])
    print("jacobi:")
    print(i[2])
    print("gauss seidel:")
    print(i[3])
    print("jacobi iterations:", i[4])
    print("gs iterations:", i[5])
    
    print("time gauss:", round(i[6], 6))
    print("time jacobi:", round(i[7], 6))
    print("time gs:", round(i[8], 6))


n = 5
gaussian elimination:
[1.03535354 1.21212121 1.23737374 1.21212121 1.03535354]
jacobi:
[1.03535347 1.21212109 1.2373736  1.21212109 1.03535347]
gauss seidel:
[1.03535345 1.21212117 1.23737372 1.21212121 1.03535353]
jacobi iterations: 13
gs iterations: 8
time gauss: 0.00016
time jacobi: 0.000155
time gs: 0.000123

n = 10
gaussian elimination:
[1.03553388 1.21320327 1.24368577 1.24891134 1.24978227 1.24978227
 1.24891134 1.24368577 1.21320327 1.03553388]
jacobi:
[1.03553383 1.21320318 1.24368563 1.24891117 1.24978209 1.24978209
 1.24891117 1.24368563 1.21320318 1.03553383]
gauss seidel:
[1.0355338  1.21320321 1.24368573 1.24891132 1.24978226 1.24978227
 1.24891134 1.24368577 1.21320327 1.03553388]
jacobi iterations: 14
gs iterations: 10
time gauss: 0.000158
time jacobi: 0.000181
time gs: 0.000572

n = 20
gaussian elimination:
[1.03553391 1.21320344 1.24368671 1.24891681 1.24981415 1.24996811
 1.24999453 1.24999906 1.24999984 1.24999997 1.24999997 1.24999984
 1.24999906 1.24999453 

```text

Ques 1 E part ans:

For small n, Gaussian elimination is very fast and gives direct accurate answer.
When n becomes large, iterative methods are better because they are simple and use less memory.
Gauss-Seidel is faster than Jacobi because it uses updated values immediately.
Matrix A is symmetric and diagonally dominant, so both Jacobi and Gauss-Seidel converge.
The convergence of iterative methods improves when matrix A is diagonally dominant, sparse, and well-structured

```

#### Question 2

In [15]:
import numpy as np

# power method...
def p(a, x):
    n = len(x)
    x = x.astype(float)
    it = 0
    while True:
        it += 1
        y = np.dot(a, x)
        m = max(abs(y))
        x2 = y / m
        if np.linalg.norm(x2 - x, np.inf) / np.linalg.norm(x, np.inf) < 1e-6:
            return m, x2, it
        if it > 100000:
            return m, x2, it
        x = x2

arr = []

a1 = np.array([
    [4,1,1,1],
    [1,3,-1,1],
    [1,-1,2,0],
    [1,1,0,2]
])
x1 = np.array([1,-2,0,3])
arr.append((a1, x1))

a2 = np.array([
    [1,3,4],
    [0,2,1],
    [0,0,-2]
])
x2 = np.array([1,1,1])
arr.append((a2, x2))

a3 = np.array([
    [3,0,0],
    [-4,6,2],
    [16,-15,-5]
])
x3 = np.array([0,0.5,0.25])
arr.append((a3, x3))

for i in range(len(arr)):
    a, x = arr[i]
    val, vec, it = p(a, x)
    print("case", i+1)
    print(f"eigenval (lamda):, {val:.3f}")
    print("vector:", vec)
    print("iterations:", it)
    print()

case 1
eigenval (lamda):, 5.236
vector: [1.         0.61803237 0.11803508 0.49999936]
iterations: 37

case 2
eigenval (lamda):, 3.625
vector: [ 1.          0.31034483 -0.20689655]
iterations: 100001

case 3
eigenval (lamda):, 1.000
vector: [ 0.   0.4 -1. ]
iterations: 2



```text

Q2 C part answer:

On analytically solving ii and iii, we get 
λ2 = 1,2,-2, dominant = 2 and λ3 = 3,1,0 , dominant = 3

Power method works correctly when there is a unique dominant eigenvalue.
Convergence depends on ratio |λ2/λ1|: smaller the ratio , faster the convergence.
In (ii), ratio is close → convergence is slower.
In (iii), ratio is smaller → faster convergence.
If initial vector has very small component in direction of dominant eigenvector, convergence can be slow or fail.
Good choice of initial vector leads to faster convergence.

```